package com.test.model;
// Generated Dec 3, 2015 9:27:08 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private Long productId;
     private Date manufacturedDate;
     private Long price;
     private String productCode;
     private String productName;
     private Long vat;
     private String brand;
     private String madeIn;

    public Product() {
    }

	
    public Product(Long productId) {
        this.productId = productId;
    }
    public Product(Long productId, Date manufacturedDate, Long price, String productCode, String productName, Long vat, String brand, String madeIn) {
       this.productId = productId;
       this.manufacturedDate = manufacturedDate;
       this.price = price;
       this.productCode = productCode;
       this.productName = productName;
       this.vat = vat;
       this.brand = brand;
       this.madeIn = madeIn;
    }
   
    public Long getProductId() {
        return this.productId;
    }
    
    public void setProductId(Long productId) {
        this.productId = productId;
    }
    public Date getManufacturedDate() {
        return this.manufacturedDate;
    }
    
    public void setManufacturedDate(Date manufacturedDate) {
        this.manufacturedDate = manufacturedDate;
    }
    public Long getPrice() {
        return this.price;
    }
    
    public void setPrice(Long price) {
        this.price = price;
    }
    public String getProductCode() {
        return this.productCode;
    }
    
    public void setProductCode(String productCode) {
        this.productCode = productCode;
    }
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }
    public Long getVat() {
        return this.vat;
    }
    
    public void setVat(Long vat) {
        this.vat = vat;
    }
    public String getBrand() {
        return this.brand;
    }
    
    public void setBrand(String brand) {
        this.brand = brand;
    }
    public String getMadeIn() {
        return this.madeIn;
    }
    
    public void setMadeIn(String madeIn) {
        this.madeIn = madeIn;
    }




}


